### ISSUE TITLE
Alignment of Modal actions

### ISSUE THREAD

**Issue by mimse** [Energinet-DataHub/greenforce-frontend#1340]
It should be possible to align modal actions left | right | center

It should also be possible to have one on the left and two on the right. So not all buttons should align the same way

ex.

![image.png](https://images.zenhubusercontent.com/633fbb34b49ff882a80234ab/25c36b4d-759f-4de5-a658-664caaa99948)

**Comment by Lubbe91** [comment]
#1371 fixed the example given in this issue.

Having a property on the modal actions control the alignment of the elements, might lead to some unintended tabbing behavior because the dom elements can be placed in any given order. 

So that will have to be handled correctly if that is the approach to follow.
