### ISSUE TITLE
Investigation of Tailwind

### ISSUE THREAD

**Issue by mimse** [Energinet-DataHub/greenforce-frontend#1746]
Try to use tailwind in our solution

**Comment by ManBearTM** [comment]
# Setup

I installed Tailwind according to Nx' instructions (https://nx.dev/recipes/other/using-tailwind-css-with-angular-projects). The setup works, but due to a bug somewhere, the developer experience is very bad. Every time you use a new Tailwind class, you have to restart the server AND delete the angular cache (or completely disable it, that works too). I was unable to fix the problem other than handling the entire process on our own using Tailwind CLI, but I would much rather that the tooling was handled by Nx/Angular, since they should support it. Maybe it has something to with our workspace setup - one could try with a new, minimal workspace and see if the issue is still there. I'm not doing anymore for now though.

# Using Tailwind with design tokens

Tailwind can either fit together nicely with design tokens or completely clash with it, depending on how design tokens are implemented. The problem lies in Tailwind's low-level utility approach - you are encouraged to avoid abstractions and design your components limited to the configured theme (https://tailwindcss.com/docs/theme). While I believe you could technically extend your theme to generate classes like `w-input-x`, I think this will make it quite confusing to use and it sort of goes against the nature of Tailwind.

If we are to use Tailwind, I see the following possible solutions:

## Only use "core level" design tokens

**Pros:**
* This fits very nicely with the Tailwind philosophy.
* We can use Tailwind to style almost everything.
* No risk of "over-engineering" the design token implementation.
* Better gains in terms of CSS bundle size since apps and watt use the same styles.

**Cons:**
* Using Tailwind in watt means consuming apps **must** support Tailwind.
* Our use of design tokens are heavily restricted.
* Some common patterns in design systems can be annoying to style with Tailwind (https://sancho.dev/blog/tailwind-and-design-systems).

## Use Tailwind in apps only (not in watt)

**Pros:**
* We can use design tokens to any degree within watt.
* We can use Tailwind to style mostly everything in apps.
* Apps do not have to support Tailwind in order to use watt.

**Cons:**
* Confusing having to work with two different ways of styling.
* Cannot use design tokens outside watt (at least not in a good way).
* Possibly "over-engineering" design tokens by applying them at component level.
* We are losing out on potential CSS bundle size benefits.

## Use Tailwind only sparingly (such as for layout)

**Pros:**
* We get access to some pretty nice utility classes.
* We can use design tokens to any degree everywhere (apps and watt).

**Cons:**
* Hard to draw the line on where to use Tailwind.
* We lose out on a lot of nice features.
* Mixing regular CSS with Tailwind is a little... oof.
* Using Tailwind in watt means consuming apps **must** support Tailwind.

## OR, do not use Tailwind at all

**Pros:**
* We can use design tokens to any degree everywhere (apps and watt).
* One less dependency.
* Cleaner HTML.

**Cons**:
* No Tailwind niceness.
* Almost requires that we create utility classes and/or layout components ourselves.
* Still risk of "over-engineering" design tokens by applying them at component level.
* CSS bundle size **possibly** worse.
